### PR TITLE
Implementing a LQ decomposition operator

### PR DESCRIPTION
**Pull request by shikharvashistha**
Added odd_or_even.hpp(header file) and odd_or_even.cpp(test file).

### CODE REVIEW

**Review by Ravenwater — CHANGES_REQUESTED** [review]
This function is not that interesting in isolation. Please provide a use-case where this function is essential.

The second problem is that this is not really linear-algebra specific, so it is questionable if this is the right place to capture this functionality.

**Comment by shikharvashistha** [comment]
Sure sir, 
As guided by you, I am trying to work out as per your guidance. I'll revert back with my work as soon as possible.

Sorry for the late reply.

Thanks & Regards 
@rainmaker6

**Comment by Ravenwater** [comment]
@rainmaker6 There is no verification test to show the use-case of this new method. How did you test this code?

**Comment by shikharvashistha** [comment]
Sir,
Will revert back to you asap.

**Review by Ravenwater — CHANGES_REQUESTED** [review]
I am still missing motivation, background description/reference, and a quick design gist so that it is clear what the scope is of your operator.

**Comment by rainmaker6** [comment]
> I am still missing motivation, background description/reference, and a quick design gist so that it is clear what the scope is of your operator.

[report.txt](https://github.com/simunova/mtl4/files/6033789/report.txt)

**Comment by shikharvashistha** [comment]
> I am still missing motivation, background description/reference, and a quick design gist so that it is clear what the scope is of your operator.

[report.txt](https://github.com/simunova/mtl4/files/6036238/report.txt)

**Review by Ravenwater — CHANGES_REQUESTED** [review]
Very nice! good motivation.

I would put the report.txt in the lq_test.cpp test application so that the two pieces of information are together: the motivation and the example application.

From that last statement you can see that the example application should demonstrate the motivation, so we need a test case that presents a solution and validation that amplifies the desire created by the motivation. Please add such a pedagogical exposition to lq_test.cpp so that another customer can look at this and step through the LQ algorithm with well-defined inputs and outputs.

**Comment by shikharvashistha** [comment]
Greetings of the day,
Thanks sir for the appreciation, I am really motivated to work further according to your advice and will try to complete the above requirements at the earliest.

With regards
@rainmaker6

**Review by Ravenwater — CHANGES_REQUESTED** [review]
the example would be much better if there is a comment section that explains the test set up and what is the expected outcome. Since this is a least squares problem, there is an overdetermined system. A description of this overdetermined system and what the LS solution does before the code does it would be most enlightening. A text picture of the data and the LS solution would be most educational.

**Comment by shikharvashistha** [comment]
> the example would be much better if there is a comment section that explains the test set up and what is the expected outcome. Since this is a least squares problem, there is an overdetermined system. A description of this overdetermined system and what the LS solution does before the code does it would be most enlightening. A text picture of the data and the LS solution would be most educational.

[test.pdf](https://github.com/simunova/mtl4/files/6073744/test.pdf)

**Comment by Ravenwater** [comment]
Love the test.pdf content, but would like to see this in the lq_test.cpp as text so that the test is self-documenting. If I am on a machine with only console access, I could not access the pdf and thus would not know the information I would need to know to interpret the lq_test.cpp file content.

**Pull request merged**
